const Menu = [
    { "name": "Fisch Suppe", "size": "normal", "price": "7,90", "currency": "€" },
    { "name": "Salat variant mit gebackenem Camembert", "size": "normal", "price": "11,90", "currency": "€" },
    { "name": "Papperdelle mit Seelachsfilet-Cherrytomaten in Knoblauchsauce", "size": "normal", "price": "13,90", "currency": "€" },
    { "name": "Fisch Platte mit Lachs, Seelachs & Gambaspieß Beilagen und Saucen nach Wahl", "size": "normal", "price": "19,90", "currency": "€" },
    { "name": "Cordon Bleu mit Pommes oder Bratkartoffeln", "size": "normal", "price": "15,90", "currency": "€" },
    { "name": "Pizza Margherita", "size": "29 cm", "price": "6,90", "currency": "€" },
    { "name": "Pizza Funghi", "size": "29 cm", "price": "8,90", "currency": "€" },
    { "name": "Pizza Salami", "size": "29 cm", "price": "8,90", "currency": "€" },
    { "name": "Pizza Prosciutto", "size": "29 cm", "price": "8,90", "currency": "€" },
    { "name": "Pizza Napoletana", "size": "29 cm", "price": "11,90", "currency": "€" },
    { "name": "Pizza Milano", "size": "29 cm", "price": "10,90", "currency": "€" },
    { "name": "Pizza Siciliana", "size": "29 cm", "price": "8,90", "currency": "€" },
    { "name": "Pizza Fantasia", "size": "29 cm", "price": "11,90", "currency": "€" },
    { "name": "Pizza Tonno e Cipolla", "size": "29 cm", "price": "10,90", "currency": "€" },
    { "name": "Pizza Frutti di Mare", "size": "29 cm", "price": "12,90", "currency": "€" },
    { "name": "Pizza Quatro Satgioni", "size": "29 cm", "price": "11,90", "currency": "€" },
    { "name": "Pizza Hawaii", "size": "29 cm", "price": "9,90", "currency": "€" },
    { "name": "Pizza Spinaci", "size": "29 cm", "price": "9,90", "currency": "€" },
    { "name": "Pizza Spezial", "size": "29 cm", "price": "12,90", "currency": "€" },
    { "name": "Pizza Capricciosa", "size": "29 cm", "price": "12,90", "currency": "€" },
    { "name": "Pizza Vegetariana", "size": "29 cm", "price": "10,90", "currency": "€" },
    { "name": "Pizza Gamberetti", "size": "29 cm", "price": "11,90", "currency": "€" },
    { "name": "Pizza Sucuk", "size": "29 cm", "price": "9,90", "currency": "€" },
    { "name": "Pizza Salmone", "size": "29 cm", "price": "12,90", "currency": "€" },
    { "name": "Pizza Mozzarella", "size": "29 cm", "price": "10,90", "currency": "€" },
    { "name": "Pizza Gambas", "size": "29 cm", "price": "12,90", "currency": "€" },
    { "name": "Pizza Casa", "size": "29 cm", "price": "12,90", "currency": "€" },
    { "name": "Pizza Rucola", "size": "29 cm", "price": "11,90", "currency": "€" },
    { "name": "Pizza Antonella", "size": "29 cm", "price": "11,90", "currency": "€" },
    { "name": "Pizza Sergio", "size": "29 cm", "price": "10,90", "currency": "€" },
    { "name": "Pizza alla Chef", "size": "29 cm", "price": "12,90", "currency": "€" },
    { "name": "Pizza Giuliano", "size": "29 cm", "price": "10,90", "currency": "€" },
    { "name": "Pizza Diabolo", "size": "29 cm", "price": "10,90", "currency": "€" },
    { "name": "Pizza Quattro Formaggi", "size": "29 cm", "price": "11,90", "currency": "€" },
    { "name": "Pizza Norwegen", "size": "29 cm", "price": "13,90", "currency": "€" },
    { "name": "Pizza Pasta Casa", "size": "29 cm", "price": "11,90", "currency": "€" },
    { "name": "Napoli", "size": "normal", "price": "7,50", "currency": "€" },
    { "name": "Bolognese", "size": "normal", "price": "9,90", "currency": "€" },
    { "name": "Aglio e Olio", "size": "normal", "price": "7,90", "currency": "€" },
    { "name": "Carbonara", "size": "normal", "price": "9,90", "currency": "€" },
    { "name": "Frutti di Mare", "size": "normal", "price": "10,90", "currency": "€" },
    { "name": "Gambas", "size": "normal", "price": "12,90", "currency": "€" },
    { "name": "Pasta alla Chef", "size": "normal", "price": "14,90", "currency": "€" },
    { "name": "Pasta al Curry", "size": "normal", "price": "11,90", "currency": "€" },
    { "name": "Pastacasa", "size": "normal", "price": "11,90", "currency": "€" },
    { "name": "Di Manzo", "size": "normal", "price": "13,90", "currency": "€" },
    { "name": "Pasta Giuliano", "size": "normal", "price": "11,90", "currency": "€" },
    { "name": "Pasta Hawaii", "size": "normal", "price": "10,90", "currency": "€" },
    { "name": "Pasta Fungi", "size": "normal", "price": "9,90", "currency": "€" },
    { "name": "Pasta Gamberreti", "size": "normal", "price": "11,90", "currency": "€" },
    { "name": "Quattro Formaggi", "size": "normal", "price": "10,90", "currency": "€" },
    { "name": "Salmone", "size": "normal", "price": "13,90", "currency": "€" },
    { "name": "Gorgonzola", "size": "normal", "price": "10,90", "currency": "€" },
    { "name": "Vegetaria", "size": "normal", "price": "9,90", "currency": "€" },
    { "name": "Milano", "size": "normal", "price": "10,90", "currency": "€" },
    { "name": "Insalata Rucola Uno", "size": "", "price": "11,90", "currency": "€" },
    { "name": "1412 Insalata Rucola Duo", "size": "", "price": "12,90", "currency": "€" },
    { "name": "Insalata Serafina", "size": "", "price": "11,90", "currency": "€" },
    { "name": "Insalata Thai", "size": "", "price": "12,90", "currency": "€" },
    { "name": "gemischter Salat", "size": "", "price": "3,90", "currency": "€" },
    { "name": "Insalata Formaggio", "size": "", "price": "9,90", "currency": "€" },
    { "name": "Insalata Mista", "size": "", "price": "7,90", "currency": "€" },
    { "name": "Insalata Capricciosa", "size": "", "price": "9,90", "currency": "€" },
    { "name": "Insalata Paesana", "size": "", "price": "9,90", "currency": "€" },
    { "name": "Insalata di Manzo", "size": "", "price": "13,90", "currency": "€" },
    { "name": "Insalata Gambas", "size": "", "price": "12,90", "currency": "€" },
    { "name": "Insalata Norvegese", "size": "", "price": "13,90", "currency": "€" },
    { "name": "Insalata della Chef", "size": "", "price": "13,90", "currency": "€" },
    { "name": "Insalata Della Casa", "size": "", "price": "11,90", "currency": "€" },
    { "name": "Portion Pommes", "size": "", "price": "4,90", "currency": "€" },
    { "name": "Bratkartoffeln", "size": "normal", "price": "4,90", "currency": "€" },
    { "name": "Portion gebratenes Gemüse", "size": "normal", "price": "4,90", "currency": "€" },
    { "name": "Knoblauchbrot", "size": "normal", "price": "3,90", "currency": "€" },
    { "name": "Portion Kräuterbutter, Jalapenos, Oliven und Peperoni", "size": "normal", "price": "4,90", "currency": "€" },
    { "name": "Lasagne", "size": "normal", "price": "11,90", "currency": "€" },
    { "name": "Curry al forno", "size": "normal", "price": "11,90", "currency": "€" },
    { "name": "Alla Chef", "size": "normal", "price": "11,90", "currency": "€" },
    { "name": "Maccheroni Gratinati", "size": "normal", "price": "11,90", "currency": "€" },
    { "name": "Pasta Casa", "size": "normal", "price": "11,90", "currency": "€" },
    { "name": "Casa Bella", "size": "normal", "price": "11,90", "currency": "€" },
    { "name": "Tris di Pasta", "size": "normal", "price": "11,90", "currency": "€" },
    { "name": "Kartoffelauflauf mit Hähnchenbruststreifen", "size": "normal", "price": "12,90", "currency": "€" },
    { "name": "Backkartoffel mit Aioli", "size": "normal", "price": "6,90", "currency": "€" },
    { "name": "Kartoffel Auflauf mit Gemüse", "size": "normal", "price": "10,90", "currency": "€" },
    { "name": "Kartoffelauflauf mit Hackfleischsauce", "size": "normal", "price": "11,90", "currency": "€" },
    { "name": "Kalbschnitzel", "size": "normal", "price": "16,90", "currency": "€" },
    { "name": "Hähnchenschnitzel nach Art des Hauses", "size": "normal", "price": "14,90", "currency": "€" },
    { "name": "Hähnchenbrustfilet vom Grill", "size": "normal", "price": "15,90", "currency": "€" },
    { "name": "Rumpsteak", "size": "normal", "price": "19,90", "currency": "€" },
    { "name": "Rumpsteak", "size": "normal", "price": "24,90", "currency": "€" },
    { "name": "Hausgemachte Frikadelle", "size": "normal", "price": "12,90", "currency": "€" },
    { "name": "Lachsfilet vom Grill", "size": "normal", "price": "16,90", "currency": "€" },
    { "name": "Zanderfilet", "size": "normal", "price": "16,90", "currency": "€" },
    { "name": "Schollenfilet Paniert", "size": "normal", "price": "12,90", "currency": "€" },
    { "name": "Aioli", "size": "normal", "price": "4,50", "currency": "€" },
    { "name": "Guacamole", "size": "normal", "price": "5,90", "currency": "€" },
    { "name": "Tomatencreme-Suppe", "size": "normal", "price": "4,90", "currency": "€" },
    { "name": "Minestrone", "size": "normal", "price": "5,90", "currency": "€" },
    { "name": "Garnelen della Casa", "size": "normal", "price": "9,90", "currency": "€" },
    { "name": "Caprese", "size": "normal", "price": "8,90", "currency": "€" },
    { "name": "Antipasti", "size": "normal", "price": "10,90", "currency": "€" },
    { "name": "Chicken BBQ - Burger", "size": "normal", "price": "12,90", "currency": "€" },
    { "name": "Rumpsteak Burger", "size": "normal", "price": "13,90", "currency": "€" },
    { "name": "Hamburger", "size": "normal", "price": "12,90", "currency": "€" },
    { "name": "Lachsburger", "size": "normal", "price": "13,90", "currency": "€" },
    { "name": "BBQ - Chicken - Wrap", "size": "normal", "price": "10,90", "currency": "€" },
    { "name": "Tomaten - Mozzarella - Wrap", "size": "normal", "price": "8,90", "currency": "€" },
    { "name": "Veggie - Wrap", "size": "normal", "price": "9,90", "currency": "€" },
    { "name": "Panna Cotta", "size": "normal", "price": "5,90", "currency": "€" },
    { "name": "Tiramisu", "size": "normal", "price": "5,90", "currency": "€" },
    { "name": "Kiddy-Box 1", "size": "normal", "price": "7,90", "currency": "€" },
    { "name": "Kiddy-Box 2", "size": "normal", "price": "7,90", "currency": "€" },
    { "name": "Schweppes Bitter Lemon", "size": "FL .1,0 L", "price": "4,40", "currency": "€" },
    { "name": "Schweppes Indian Tonic Water", "size": "FL .1,0 L", "price": "4,40", "currency": "€" },
    { "name": "Schweppes American Ginger", "size": "FL .1,0 L", "price": "4,40", "currency": "€" },
    { "name": "Erdinger Kristall", "size": "FL .0,5 L", "price": "2,80", "currency": "€" },
    { "name": "Erdinger Dunkel", "size": "FL .0,5 L", "price": "2,80", "currency": "€" },
    { "name": "Heineken", "size": "FL .0,33 L", "price": "2,80", "currency": "€" },
    { "name": "Desperados", "size": "FL .0,33 L", "price": "3,60", "currency": "€" },
    { "name": "Erdinger Weizen Alkoholfrei", "size": "FL .0,5 L", "price": "2,80", "currency": "€" },
    { "name": "Bitburger Alkoholfrei 0.0%", "size": "FL .0,33 L", "price": "2,90", "currency": "€" },
    { "name": "Vita Malz Alkoholfrei", "size": "FL .0,33 L", "price": "2,40", "currency": "€" },
    { "name": "Fassbrause Alkoholfrei", "size": "FL .0,33 L", "price": "2,40", "currency": "€" },
    { "name": "Coca Cola", "size": "FL .1,0 L", "price": "3,60", "currency": "€" },
    { "name": "Cola Light", "size": "FL .1,0 L", "price": "3,60", "currency": "€" },
    { "name": "Cola Zero", "size": "FL .1,0 L", "price": "3,60", "currency": "€" },
    { "name": "Fanta", "size": "FL .1,0 L", "price": "3,60", "currency": "€" },
    { "name": "Sprite", "size": "FL .1,0 L", "price": "3,60", "currency": "€" },
    { "name": "Gerolsteiner Mineralwasser", "size": "FL .0,7 L", "price": "2,80", "currency": "€" },
    { "name": "Früh Kölsch", "size": "FL .0,5 L", "price": "2,40", "currency": "€" },
    { "name": "Bitburger Pils", "size": "FL .0,5 L", "price": "2,40", "currency": "€" },
    { "name": "Beck's", "size": "FL .0,5 L", "price": "2,50", "currency": "€" },
    { "name": "Erdinger Weizen", "size": "FL .0,5 L", "price": "2,80", "currency": "€" },
    { "name": "Rotwein", "size": "FL .0,7 L", "price": "7,90", "currency": "€" },
    { "name": "Weißwein", "size": "FL .0,7 L", "price": "7,90", "currency": "€" },
    { "name": "Rosewein", "size": "FL .0,7 L", "price": "7,90", "currency": "€" },
    { "name": "Lambrusco", "size": "FL .0,7 L", "price": "7,90", "currency": "€" }
]